# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_auto_20170904_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
