# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0006_auto_20170905_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
