# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import wines.models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0004_auto_20170904_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='abv',
            field=models.CharField(default=10, max_length=2, validators=[wines.models.valid_pct]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='colour',
            field=models.CharField(default='red', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='grape',
            field=models.CharField(default='red', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='mode_rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='region_country',
            field=models.CharField(default='aus', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='winner',
            field=models.CharField(default='me', max_length=50),
            preserve_default=False,
        ),
    ]
