# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0007_wine_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='region_country',
            new_name='region',
        ),
    ]
